// PRADAR 24-item standard seed
export const PRADAR_SEEDS: { proof: string; coListWith?: ("tsa" | "notice")[] }[] = [
  { proof: "Budget allocation document / Resource Allocation Plans" },
  { proof: "Signed policy or statements of commitment to data privacy; Data privacy implementation plans or compliance roadmaps endorsed by management; or Meeting minutes showing management discussion or approval of data privacy initiatives." },
  { proof: "Appointment Papers / Contract of the DPO and/or DPO team (Notarized)" },
  { proof: "Duties and responsibilities in the Appointment Papers / Contract of the DPO / Privacy Manual" },
  { proof: "Documented Escalation / Reporting Procedure", coListWith: ["tsa"] },
  { proof: "Records of Processing Activities (RoPA) / Data Processing Systems Inventory" },
  { proof: "NPC Certificate of Registration and Seal of Registration; DPS Registration via NPC-RS" },
  { proof: "PIA Report" },
  { proof: "Privacy Manual / Data Protection Policies (Security, Access Control, Acceptable Use, Password, BCP, Telecommuting, CCTV, Retention, Privacy-By-Design/Default)", coListWith: ["tsa"] },
  { proof: "Data center & storage areas with limited physical access; technical security report; firewalls; encryption (transit/rest); access policy onsite/remote/online; audit logs; backup solutions; internal audit reports; certifications (ISO 27001, NPC Privacy Mark); VA & pen-test reports; other measures.", coListWith: ["tsa"] },
  { proof: "Number of employees who attended privacy training / Training Attendance Sheet; DPA commitment in Code of Conduct or signed document per employee record" },
  { proof: "NDAs or confidentiality agreements; Security Clearance / Access Control Policy" },
  { proof: "Certificate of Training of DPO; Certifications of DPOs" },
  { proof: "Schedule of breach drills; # of trainings on breach management; Personnel Order constituting DBRT; Incident Response Policy & Procedure", coListWith: ["tsa"] },
  { proof: "Record of Security incidents and personal data breaches incl. notifications / Annual Security Incident Report (ASIR)", coListWith: ["tsa"] },
  { proof: "Data Sharing Agreements; Model Contractual Clauses for Cross-Border Transfers; List of recipients of personal data (PIPs, PICs, providers, gov agencies)" },
  { proof: "Data Outsourcing / Subcontracting Agreements or formal contracts" },
  { proof: "Privacy Notice on website and/or organization (where personal data is collected) and CCTV Notice (if applicable); Visible announcement displaying DPO's contact details", coListWith: ["notice"] },
  { proof: "Procedures for obtaining consent and a Consent Form (may be in Privacy Manual)" },
  { proof: "Form or platform for data subjects to exercise rights & Request Form; Policies and procedures for third-party requests (media, law enforcement, representatives) & Request Form" },
  { proof: "Policy on conduct of Internal Assessments and Security Audits; Privacy Manual regular review policy" },
  { proof: "Proof of annual review/update of RoPA, DPS Inventory, PIA, Privacy Manual, PMP, Privacy Notice, Consent Forms, Outsourcing/Sharing Agreements" },
  { proof: "PMP Compliance / Gap / Maturity Assessment" },
  { proof: "Number of trainings & conferences on data privacy attended; Policy / position / research papers on emerging tech, best practices, sector standards, international standards" },
];
